// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import {Avatar, version, Dropdown, Menu, Spin} from 'antd';
import {LogoutOutlined} from '@ant-design/icons';
import cookie from "js-cookie";

export function getAvatarRenderContent(opts: {
    runtimeConfig?: any,
    loading?: boolean,
    initialState?: any,
    setInitialState?: any,
    logout?: () => void
}) {

    const token = cookie.get('Authorization')
    const avatar = (
        <div>
            <Avatar
                size="small"
                crossOrigin={"use-credentials"}
                src={
                    opts.initialState?.avatar?`${opts.initialState?.avatar}?authorization=${token}` :
                    ''
                }
                alt="avatar"
            />
            <span style={{marginLeft:8}}>{opts.initialState?.name}</span>
        </div>
    );

    if (opts.loading) {
        return (
            <div className="umi-plugin-layout-right">
                <Spin size="small" style={{marginLeft: 8, marginRight: 8}}/>
            </div>
        );
    }

    const langMenu = {
        // className: "umi-plugin-layout-menu",
        selectedKeys: [],
        items: [
            {
                key: "logout",
                icon: <LogoutOutlined />,
                label: (
                    <>
                        退出登录
                    </>
                ),
                onClick: () => {
                    opts?.logout?.(opts.initialState);
                },
            },
        ],
    };
    // antd@5 和  4.24 之后推荐使用 menu，性能更好
    const dropdownProps =
        version.startsWith("5.") || version.startsWith("4.24.")
            ? {menu: langMenu}
            : {overlay: <Menu {...langMenu} />};

    return (
        <>
            {opts?.logout ? (
                <Dropdown {...dropdownProps} overlayClassName="umi-plugin-layout-container">
                    {avatar}
                </Dropdown>
            ) : (
                avatar
            )}
        </>
    );
}
